import 'package:flutter/material.dart';
import '../theme/app_colors.dart';

class ParcelPage extends StatefulWidget { const ParcelPage({super.key}); @override State<ParcelPage> createState() => _ParcelPageState(); }
class _ParcelPageState extends State<ParcelPage> { bool express = false;
 @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Send a parcel'), centerTitle: true), body: ListView(padding: const EdgeInsets.all(20), children: [
  Container(padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: const Color(0xFFFFF4E4), borderRadius: BorderRadius.circular(18)), child: const Row(children: [Icon(Icons.inventory_2_outlined, color: Color(0xFFB96700), size: 35), SizedBox(width: 13), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Local delivery, made simple', style: TextStyle(fontWeight: FontWeight.w800)), SizedBox(height: 4), Text('Send small parcels safely via Trigo e-rickshaw.', style: TextStyle(fontSize: 12, color: Colors.black54))]))])), const SizedBox(height: 22), const Text('PICKUP & DROP', style: TextStyle(fontSize: 11, letterSpacing: 1, fontWeight: FontWeight.bold, color: Colors.black54)), const SizedBox(height: 10),
  const _AddressRow(color: AppColors.green, title: 'Pickup location', value: 'Sector 62 Metro Station'), const _AddressRow(color: Color(0xFFFF8A45), title: 'Drop location', value: 'Gaur City Mall, Gate 2'), const SizedBox(height: 18), const Text('PARCEL DETAILS', style: TextStyle(fontSize: 11, letterSpacing: 1, fontWeight: FontWeight.bold, color: Colors.black54)), const SizedBox(height: 10),
  Container(padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(16), border: Border.all(color: const Color(0xFFE5E9E6))), child: const Row(children: [Icon(Icons.shopping_bag_outlined), SizedBox(width: 13), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Small package', style: TextStyle(fontWeight: FontWeight.w700)), Text('Documents, food, gifts or essentials', style: TextStyle(fontSize: 12, color: Colors.black54))])), Icon(Icons.keyboard_arrow_down)])), const SizedBox(height: 20), SwitchListTile(value: express, contentPadding: EdgeInsets.zero, activeThumbColor: AppColors.green, onChanged: (v) => setState(() => express = v), title: const Text('Express delivery', style: TextStyle(fontWeight: FontWeight.w700)), subtitle: const Text('Priority pickup within 15 minutes'), secondary: const Icon(Icons.bolt, color: Color(0xFFFFAD31))), const SizedBox(height: 18), SizedBox(height: 54, child: FilledButton(onPressed: () => _showParcelBooked(context), child: Text(express ? 'Send express  ·  ₹69' : 'Send parcel  ·  ₹49'))),
 ]));
 void _showParcelBooked(BuildContext context) => showModalBottomSheet(context: context, showDragHandle: true, builder: (_) => Padding(padding: const EdgeInsets.fromLTRB(24, 8, 24, 34), child: Column(mainAxisSize: MainAxisSize.min, children: [const CircleAvatar(radius: 31, backgroundColor: AppColors.softGreen, child: Icon(Icons.check, color: AppColors.green, size: 34)), const SizedBox(height: 15), const Text('Parcel pickup confirmed!', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w800)), const SizedBox(height: 8), const Text('Ravi will collect your package in 7 minutes.', textAlign: TextAlign.center), const SizedBox(height: 22), SizedBox(width: double.infinity, child: FilledButton(onPressed: () { Navigator.pop(context); Navigator.pop(context); }, child: const Text('Done')))])));
}
class _AddressRow extends StatelessWidget { const _AddressRow({required this.color, required this.title, required this.value}); final Color color; final String title, value; @override Widget build(BuildContext context) => Container(margin: const EdgeInsets.only(bottom: 8), padding: const EdgeInsets.all(14), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(14), border: Border.all(color: const Color(0xFFE5E9E6))), child: Row(children: [Container(width: 12, height: 12, decoration: BoxDecoration(color: color, shape: BoxShape.circle)), const SizedBox(width: 13), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(fontSize: 11, color: Colors.black54)), const SizedBox(height: 3), Text(value, style: const TextStyle(fontWeight: FontWeight.w700))]))])); }
