import 'package:flutter/material.dart';
import '../theme/app_colors.dart';
import 'tracking_page.dart';

class RideBookingPage extends StatefulWidget { const RideBookingPage({super.key}); @override State<RideBookingPage> createState() => _RideBookingPageState(); }
class _RideBookingPageState extends State<RideBookingPage> {
  int choice = 0;
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Book a ride'), centerTitle: true), body: Column(children: [
    Container(height: 220, margin: const EdgeInsets.all(20), decoration: BoxDecoration(color: const Color(0xFFDFF3E9), borderRadius: BorderRadius.circular(22)), child: Stack(children: [const Positioned(left: 35, top: 38, child: Icon(Icons.location_on, color: AppColors.green)), const Positioned(right: 45, bottom: 32, child: Icon(Icons.location_pin, color: Color(0xFFFF8A45))), Center(child: Icon(Icons.electric_rickshaw, color: AppColors.green.withOpacity(.55), size: 104)), const Positioned(left: 70, top: 75, child: _MapLine()), const Positioned(right: 62, bottom: 75, child: _MapLine())])),
    Expanded(child: Container(decoration: const BoxDecoration(color: Colors.white, borderRadius: BorderRadius.vertical(top: Radius.circular(28))), padding: const EdgeInsets.fromLTRB(20, 22, 20, 10), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Choose your Trigo', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w800)), const SizedBox(height: 12), _RideOption(selected: choice == 0, title: 'Trigo Eco', detail: '3 min away  •  2 seats', price: '₹42', icon: Icons.electric_rickshaw, onTap: () => setState(() => choice = 0)), _RideOption(selected: choice == 1, title: 'Trigo Share', detail: '5 min away  •  Save more', price: '₹28', icon: Icons.groups_2_outlined, onTap: () => setState(() => choice = 1)), const Spacer(), SizedBox(width: double.infinity, height: 54, child: FilledButton(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const TrackingPage())), child: Text(choice == 0 ? 'Book Trigo Eco  ·  ₹42' : 'Book Trigo Share  ·  ₹28')))])))
  ]));
}
class _MapLine extends StatelessWidget { const _MapLine(); @override Widget build(BuildContext context) => Transform.rotate(angle: -.75, child: Container(width: 100, height: 3, color: AppColors.green.withOpacity(.55))); }
class _RideOption extends StatelessWidget { const _RideOption({required this.selected, required this.title, required this.detail, required this.price, required this.icon, required this.onTap}); final bool selected; final String title, detail, price; final IconData icon; final VoidCallback onTap; @override Widget build(BuildContext context) => InkWell(onTap: onTap, borderRadius: BorderRadius.circular(16), child: Container(margin: const EdgeInsets.only(bottom: 10), padding: const EdgeInsets.all(14), decoration: BoxDecoration(border: Border.all(color: selected ? AppColors.green : const Color(0xFFE4E8E5), width: selected ? 2 : 1), borderRadius: BorderRadius.circular(16)), child: Row(children: [CircleAvatar(backgroundColor: AppColors.softGreen, child: Icon(icon, color: AppColors.green)), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(fontWeight: FontWeight.w800)), const SizedBox(height: 4), Text(detail, style: const TextStyle(fontSize: 12, color: Colors.black54))])), Text(price, style: const TextStyle(fontWeight: FontWeight.w800, fontSize: 16))]))); }
